### ISSUE TITLE
Minimum SDK too high

### ISSUE THREAD

**Issue by larrytech7** [feelcoder/pregnancyTestApp#1]
I should be able to run the app on android version prior to version 5.0 but no earlier than version 4.0 API level 14+. This is currently not he case and so the minimum SDK level needs to be reduced in your gradle file.

**Comment by feelcoder** [comment]
Aright @larrytech7 I will make the change. Were you able to run the app?

**Comment by feelcoder** [comment]
@larrytech7 The change was made, I guess I have to mail you the new version of the application

**Comment by larrytech7** [comment]
All good.
